
name: 'Build src'
description: 'Build src!'
inputs:
  refresh:
    description: 'Should the R/stanmodels.R file be refreshed'
    default: true
runs:
  using: "composite"
  steps:

    - name: Cache Compiled Stan Code
      id: cache-pkgs
      uses: actions/cache@v3
      with:
        path: local/*
        key: ${{ hashFiles('inst/stan/MMRM.stan') }}

    - name: Build if needed
      shell: bash
      env:
        RBMI_CACHE_DIR: local
      run: |
        Rscript -e "pkgload::load_all(); get_stan_model()"
