
name: 'Build src'
description: 'Build src!'
inputs:
  refresh:
    description: 'Should the R/stanmodels.R file be refreshed'
    default: true
runs:
  using: "composite"
  steps:

    - name: Determine system/package state
      run: |
        sink(".github/meta.txt")
            list(
                version = version,
                pkgs = installed.packages()[c("rstan"), c("Version", "Package")]
            )
        sink()
      shell: Rscript {0}

    - name: Cache Compiled Stan Code
      id: cache-pkgs
      uses: actions/cache@v3
      with:
        path: local/*
        key: ${{ hashFiles('.github/meta.txt') }}-${{ hashFiles('inst/stan/MMRM.stan') }}

    - name: Build if needed
      shell: bash
      env:
        RBMI_CACHE_DIR: local
      run: |
        Rscript -e "pkgload::load_all(); get_stan_model()"
