#' Analysis of Covariance
#'
#' Performs an analysis of covariance between two or more treatment groups returning the
#' estimated "treatment effect" (i.e. the contrast between treatment groups) and
#' the least square means estimates in each group.
#'
#' @param data A `data.frame` containing the data to be used in the model.
#' @param vars A `vars` object as generated by [set_vars()]. Only the `group`,
#' `visit`, `outcome` and `covariates` elements are required. See details.
#' @param visits An optional character vector specifying which visits to
#' fit the ANCOVA model at. If `NULL`, a separate ANCOVA model will be fit to the
#' outcomes for each visit (as determined by `unique(data[[vars$visit]])`).
#' See details.
#' @param weights Character, either `"counterfactual"` (default), `"equal"`,
#' `"proportional_em"` or `"proportional"`.
#' Specifies the weighting strategy to be used when calculating the lsmeans.
#' See the weighting section for more details.
#'
#' @details
#' The function works as follows:
#'
#' 1. Select the first value from `visits`.
#' 2. Subset the data to only the observations that occurred on this visit.
#' 3. Fit a linear model as  `vars$outcome ~ vars$group + vars$covariates`.
#' 4. Extract the "treatment effect" & least square means for each treatment group.
#' 5. Repeat points 2-3 for all other values in `visits`.
#'
#' If no value for `visits` is provided then it will be set to
#' `unique(data[[vars$visit]])`.
#'
#' In order to meet the formatting standards set by [analyse()] the results will be collapsed
#' into a single list suffixed by the visit name, e.g.:
#'```
#'list(
#'    trt_visit_1 = list(est = ...),
#'    lsm_ref_visit_1 = list(est = ...),
#'    lsm_alt_visit_1 = list(est = ...),
#'    trt_visit_2 = list(est = ...),
#'    lsm_ref_visit_2 = list(est = ...),
#'    lsm_alt_visit_2 = list(est = ...),
#'    ...
#')
#'```
#' `ancova()` supports two or more treatment groups. The group levels are referred to
#' via a fixed naming scheme derived from the factor levels of `vars$group`: `ref` is the
#' first factor level, `alt` the second, `alt2` the third, `alt3` the fourth, and so on.
#' Note that `ref` does not necessarily coincide with the control arm; it is simply the
#' first factor level.
#'
#' The least square means for each group are returned as `lsm_ref`, `lsm_alt`, `lsm_alt2`,
#' etc. Treatment effects (model contrasts) are returned as `trt` for the `alt` vs `ref`
#' comparison, `trt_alt2` for `alt2` vs `ref`, and so on. For the common case of two groups
#' this reduces to the original `trt`, `lsm_ref` and `lsm_alt` naming, ensuring backwards
#' compatibility.
#'
#' By default a treatment effect is calculated for every non-reference group versus the
#' reference group, using the `trt` / `trt_alt2` / ... names described above. Alternatively
#' a bespoke set of contrasts can be requested via the `group_contrasts` argument of
#' [set_vars()]; see its documentation for details. Such contrasts must be named, and the
#' supplied name is used as the `parameter` name and carried through to the
#' `contrast_label` column of the [pool()] output. Contrasts may be pairwise (a length-2
#' `c(minuend, subtrahend)` character vector) or general linear contrasts (a named numeric
#' weight vector over the group levels).
#'
#' If you want to include interaction terms in your model this can be done
#' by providing them to the `covariates` argument of [set_vars()]
#' e.g. `set_vars(covariates = c("sex*age"))`.
#'
#' Note that the treatment effects (`trt`, `trt_alt2`, ...) are the relevant linear
#' combinations of the model coefficients, i.e. the group main-effect contrasts evaluated
#' at the reference level of any covariates. The least square means (`lsm_*`) are instead
#' computed according to the requested `weights`. When `group` interacts with a covariate
#' these two quantities differ, so `trt` is not in general equal to `lsm_alt - lsm_ref`.
#' This matches the behaviour of the original two-group implementation, where `trt` has
#' always been the model coefficient.
#'
#' @inheritSection lsmeans Weighting
#'
#' @seealso [analyse()]
#' @seealso [stats::lm()]
#' @seealso [set_vars()]
#' @return
#' A named list with one set of entries per visit, each suffixed by the visit name.
#' For each visit the list contains:
#'
#' - the estimated treatment effect(s). For the default (`group_contrasts = NULL`) these
#'   are `trt_<visit>` for the `alt` vs `ref` comparison and `trt_alt2_<visit>`,
#'   `trt_alt3_<visit>`, ... for further non-reference groups versus the reference group.
#'   When `group_contrasts` is supplied each contrast is named `<name>_<visit>` using the
#'   list name given for that contrast. Also
#' - the least square means for each group (`lsm_ref_<visit>`, `lsm_alt_<visit>`,
#'   `lsm_alt2_<visit>`, ...).
#'
#' For the common case of two groups this reduces to `trt_<visit>`, `lsm_ref_<visit>`
#' and `lsm_alt_<visit>`. Each of these elements is itself a list holding the estimate
#' (`est`), standard error (`se`) and degrees of freedom (`df`).
#'
#' @examples
#' # Simulate a small dataset with a single visit, a treatment group and a
#' # baseline covariate to adjust for.
#' set.seed(101)
#' dat <- data.frame(
#'     visit = factor("visit_1"),
#'     group = factor(rep(c("Control", "Intervention"), each = 50)),
#'     basval = rnorm(100)
#' )
#' dat$outcome <- 5 + 2 * (dat$group == "Intervention") + dat$basval + rnorm(100)
#'
#' vars <- set_vars(
#'     outcome = "outcome",
#'     group = "group",
#'     visit = "visit",
#'     covariates = "basval"
#' )
#'
#' # Estimated treatment effect and least square means for the single visit.
#' # In a full `rbmi` analysis, `ancova()` is passed to `analyse()` rather than
#' # called directly; see [analyse()].
#' ancova(dat, vars)
#'
#' # Multi-arm ANCOVA with a bespoke, named set of contrasts. With three groups
#' # the default would compare each active arm against the reference ("Placebo");
#' # here we additionally request the "High" vs "Low" contrast. Explicit contrasts
#' # must be named, and the names become the output parameter names.
#' set.seed(102)
#' dat3 <- data.frame(
#'     visit = factor("visit_1"),
#'     group = factor(
#'         rep(c("Placebo", "Low", "High"), each = 50),
#'         levels = c("Placebo", "Low", "High")
#'     ),
#'     basval = rnorm(150)
#' )
#' dat3$outcome <- 5 +
#'     2 * (dat3$group == "Low") +
#'     4 * (dat3$group == "High") +
#'     dat3$basval +
#'     rnorm(150)
#'
#' vars3 <- set_vars(
#'     outcome = "outcome",
#'     group = "group",
#'     visit = "visit",
#'     covariates = "basval",
#'     group_contrasts = list(
#'         low_vs_pbo  = c("Low", "Placebo"),
#'         high_vs_pbo = c("High", "Placebo"),
#'         high_vs_low = c("High", "Low")
#'     )
#' )
#'
#' # Output names: `low_vs_pbo`, `high_vs_pbo`, `high_vs_low`, plus
#' # `lsm_ref` / `lsm_alt` / `lsm_alt2`.
#' names(ancova(dat3, vars3))
#'
#' @export
ancova <- function(
    data,
    vars,
    visits = NULL,
    weights = c("counterfactual", "equal", "proportional_em", "proportional")
) {
    ancova_core(
        data = data,
        vars = vars,
        visits = visits,
        weights = weights
    )
}


#' Core ANCOVA Implementation
#'
#' Internal function that provides the common functionality for the (multi-arm) ANCOVA
#' analysis. This function handles input validation, visit processing, delegates the
#' actual single-visit analysis to [ancova_single()], and assembles the per-parameter
#' metadata.
#'
#' @inheritParams ancova
#'
#' @keywords internal
ancova_core <- function(
    data,
    vars,
    visits = NULL,
    weights = c("counterfactual", "equal", "proportional_em", "proportional")
) {
    outcome <- vars[["outcome"]]
    group <- vars[["group"]]
    covariates <- vars[["covariates"]]
    visit <- vars[["visit"]]
    group_contrasts <- vars[["group_contrasts"]]
    weights <- match.arg(weights)

    expected_vars <- c(extract_covariates(covariates), outcome, group)

    assert_that(
        !any(visit %in% expected_vars),
        msg = paste0(
            "The `vars$visit` variable cannot be a covariate in an ANCOVA model. ",
            "Please adjust `vars$covariates` accordingly"
        )
    )

    for (var in c(visit, expected_vars)) {
        assert_that(
            var %in% names(data),
            msg = sprintf("Variable `%s` doesn't exist in data", var)
        )
    }

    assert_that(
        is.character(outcome),
        length(outcome) == 1,
        msg = "`vars$outcome` must be a length 1 character"
    )

    assert_that(
        is.character(group),
        length(group) == 1,
        msg = "`vars$group` must be a length 1 character"
    )

    assert_that(
        is.character(visit),
        length(visit) == 1,
        msg = "`vars$visit` must be a length 1 character"
    )

    assert_that(
        is.character(covariates) | is.null(covariates),
        msg = "`covariates` must be a character vector"
    )

    assert_that(
        is.null(visits) | is.character(visits),
        msg = "`visits` must be NULL or a character vector"
    )

    if (is.null(visits)) {
        visits <- unique(data[[visit]])
    }

    for (i in visits) {
        assert_that(
            i %in% data[[visit]],
            msg = sprintf(
                "Visit `%s` does not appear in `data[[vars$visit]]`",
                i
            )
        )
    }

    res <- lapply(
        visits,
        function(x) {
            data2 <- data[data[[visit]] == x, ]
            fit <- ancova_single(
                data2,
                outcome,
                group,
                covariates,
                weights,
                group_contrasts
            )
            meta <- attr(fit, "rbmi_par_meta")
            names(fit) <- paste0(names(fit), "_", x)
            meta[["parameter"]] <- paste0(meta[["parameter"]], "_", x)
            meta[["visit"]] <- x
            attr(fit, "rbmi_par_meta") <- meta
            fit
        }
    )
    par_meta <- do.call(rbind, lapply(res, attr, "rbmi_par_meta"))
    par_meta[["group"]] <- group
    par_meta <- par_meta[,
        c(
            "parameter",
            "estimate_type",
            "group",
            "group_level_1",
            "group_level_2",
            "contrast_label",
            "visit"
        )
    ]
    rownames(par_meta) <- NULL

    out <- unlist(res, recursive = FALSE)
    attr(out, "rbmi_par_meta") <- par_meta
    return(out)
}


#' Implements an Analysis of Covariance (ANCOVA)
#'
#' @description
#' Performance analysis of covariance. See [ancova()] for full details.
#'
#' @param outcome Character, the name of the outcome variable in `data`.
#' @param group Character, the name of the group variable in `data`.
#' @param covariates Character vector containing the name of any additional covariates
#' to be included in the model as well as any interaction terms.
#'
#' @inheritParams ancova
#' @inheritSection lsmeans Weighting
#'
#' @param group_contrasts Optional list specifying bespoke treatment-group contrasts.
#' See [set_vars()] and [ancova()] for details. If `NULL` (default) a contrast of each
#' non-reference group versus the reference group is calculated.
#'
#' @details
#' - `group` must be a factor variable with two or more levels, all of which must be
#'   observed in the data.
#' - `outcome` must be a continuous numeric variable.
#'
#' The group levels are mapped to a fixed set of labels (`ref`, `alt`, `alt2`, ...) based
#' on the factor level ordering; see [ancova()] for the resulting naming scheme.
#'
#' @section Reserved Variable Names:
#' This function uses `"rbmiGroup"` as an internal variable name. If your dataset
#' contains a variable with this name, the function will error.
#'
#' @examples
#' \dontrun{
#' iris2 <- iris[ iris$Species %in% c("versicolor", "virginica"), ]
#' iris2$Species <- factor(iris2$Species)
#' ancova_single(iris2, "Sepal.Length", "Species", c("Petal.Length * Petal.Width"))
#' }
#' @seealso [ancova()]
#' @importFrom stats lm coef vcov df.residual
#' @keywords internal
ancova_single <- function(
    data,
    outcome,
    group,
    covariates,
    weights = c("counterfactual", "equal", "proportional_em", "proportional"),
    group_contrasts = NULL
) {
    weights <- match.arg(weights)
    assert_that(
        is.factor(data[[group]]),
        length(levels(data[[group]])) >= 2,
        length(unique(data[[group]])) == length(levels(data[[group]])),
        msg = paste(
            "`data[[vars$group]]` must be a factor variable with two or more levels,",
            "all of which must be observed in the data"
        )
    )
    assert_that(
        !"rbmiGroup" %in% names(data),
        msg = paste(
            "`rbmiGroup` is a reserved variable name for internal use, please rename",
            "your variable to avoid conflicts"
        )
    )

    orig_levels <- levels(data[[group]])
    n_lvl <- length(orig_levels)
    labels <- ancova_group_labels(n_lvl)
    intcode <- paste0("L", seq_len(n_lvl))

    # Standardise the group levels + variable name so that coefficient / term
    # extraction is robust to whitespace or special characters in the user levels.
    data2 <- data[, c(extract_covariates(covariates), outcome, group)]
    data2[["rbmiGroup"]] <- factor(
        intcode[as.integer(data2[[group]])],
        levels = intcode
    )
    data2 <- data2[!names(data2) %in% group]

    frm <- as_simple_formula(outcome, c(covariates, group))
    frm <- frm_find_and_replace(frm, as.name(group), as.name("rbmiGroup"))

    mod <- lm(formula = frm, data = data2)
    beta <- coef(mod)
    vcov_mod <- vcov(mod)
    df_res <- df.residual(mod)

    # Identify the model coefficients belonging to the `rbmiGroup` main effect and
    # the factor's own contrast matrix. This lets contrasts be formed in a
    # coding-agnostic way (independent of the active `contrasts` option) rather
    # than by parsing coefficient names.
    mm_assign <- attr(stats::model.matrix(mod), "assign")
    term_labels <- attr(stats::terms(mod), "term.labels")
    grp_term <- which(term_labels == "rbmiGroup")
    assert_that(
        length(grp_term) == 1,
        msg = "internal error: `rbmiGroup` main effect not found in the model"
    )
    grp_names <- names(beta)[mm_assign == grp_term]
    cmat <- stats::contrasts(data2[["rbmiGroup"]])

    # Least square means for every group level
    lsm <- lapply(intcode, function(code) {
        args <- list(model = mod, .weights = weights)
        args[["rbmiGroup"]] <- code
        do.call(lsmeans, args)
    })
    names(lsm) <- paste0("lsm_", labels)

    # Resolve the requested contrasts to weight vectors over the group levels.
    contrasts <- ancova_resolve_contrasts(group_contrasts, orig_levels, labels)

    trt <- lapply(contrasts, function(ct) {
        ancova_linear_contrast(
            ct[["weights"]],
            beta,
            vcov_mod,
            df_res,
            grp_names,
            cmat
        )
    })
    names(trt) <- vapply(
        contrasts,
        function(ct) ct[["parameter"]],
        character(1)
    )

    res <- append(trt, lsm)

    # Parameter metadata (uses the actual group level labels, not ref/alt)
    meta_trt <- data.frame(
        parameter = names(trt),
        estimate_type = "contrast",
        contrast_label = vapply(
            contrasts,
            function(ct) ct[["label"]],
            character(1)
        ),
        group_level_1 = vapply(
            contrasts,
            function(ct) ct[["level_1"]],
            character(1)
        ),
        group_level_2 = vapply(
            contrasts,
            function(ct) ct[["level_2"]],
            character(1)
        ),
        stringsAsFactors = FALSE
    )
    meta_lsm <- data.frame(
        parameter = names(lsm),
        estimate_type = "lsm",
        contrast_label = NA_character_,
        group_level_1 = orig_levels,
        group_level_2 = NA_character_,
        stringsAsFactors = FALSE
    )
    attr(res, "rbmi_par_meta") <- rbind(meta_trt, meta_lsm)
    res
}


#' ANCOVA group level labels
#'
#' Maps the ordered factor levels of the group variable to the fixed `rbmi` label
#' scheme: the first level is `ref`, the second `alt`, and any further levels
#' `alt2`, `alt3`, etc.
#'
#' @param n Integer, the number of group levels.
#' @return A character vector of labels of length `n`.
#' @keywords internal
ancova_group_labels <- function(n) {
    vapply(
        seq_len(n),
        function(i) {
            if (i == 1) {
                "ref"
            } else if (i == 2) {
                "alt"
            } else {
                paste0("alt", i - 1)
            }
        },
        character(1)
    )
}


#' Name a default ANCOVA treatment-effect contrast
#'
#' Determines the `parameter` name for a default contrast of a non-reference level against
#' the reference level: the second factor level is `trt`, the third `trt_alt2`, the fourth
#' `trt_alt3`, and so on. Only used for the default (`group_contrasts = NULL`) set;
#' user-supplied contrasts are named explicitly by the caller.
#'
#' @param i Integer, 1-based index of the (non-reference) group level.
#' @param labels Character vector of level labels as returned by [ancova_group_labels()].
#' @return A length 1 character vector with the parameter name.
#' @keywords internal
ancova_contrast_name <- function(i, labels) {
    if (i == 2) {
        "trt"
    } else {
        paste0("trt_", labels[i])
    }
}


#' Resolve the set of ANCOVA contrasts to compute
#'
#' Translates the optional `group_contrasts` specification into a list of contrast
#' records. Each record holds a weight vector over the group levels (`weights`, in
#' factor-level order, summing to zero), the output `parameter` name, an optional
#' user `label`, and the `level_1` / `level_2` group labels for simple pairwise
#' contrasts (`NA` for general weight-vector contrasts).
#'
#' When `group_contrasts` is `NULL` the default is each non-reference level versus the
#' reference level, using the backwards-compatible `trt` / `trt_alt2` / ... naming.
#' Otherwise the list must be fully named; each element is either a length-2 character
#' vector `c(minuend, subtrahend)` (a pairwise contrast) or a numeric weight vector over
#' the group levels, and the list name is used as the `parameter` name.
#'
#' @param group_contrasts Either `NULL` or a fully named list of length-2 character
#'   vectors and/or numeric weight vectors. See [set_vars()].
#' @param orig_levels Character vector of the group factor levels (in order).
#' @param labels Character vector of `ref`/`alt`/... labels from [ancova_group_labels()].
#' @return A list of contrast records (see description).
#' @keywords internal
ancova_resolve_contrasts <- function(group_contrasts, orig_levels, labels) {
    n_lvl <- length(orig_levels)
    record <- function(weights, parameter, label, level_1, level_2) {
        list(
            weights = weights,
            parameter = parameter,
            label = label,
            level_1 = level_1,
            level_2 = level_2
        )
    }
    pairwise_weights <- function(i, j) {
        w <- numeric(n_lvl)
        w[i] <- 1
        w[j] <- -1
        w
    }

    # Default: each non-reference level vs the reference, using the derived
    # `trt` / `trt_alt2` / ... names (the only place derived names are used).
    if (is.null(group_contrasts)) {
        return(lapply(seq_len(n_lvl)[-1], function(i) {
            record(
                pairwise_weights(i, 1L),
                ancova_contrast_name(i, labels),
                NA_character_,
                orig_levels[i],
                orig_levels[1]
            )
        }))
    }

    nms <- names(group_contrasts)
    assert_that(
        is.list(group_contrasts),
        length(group_contrasts) >= 1,
        !is.null(nms) && all(nzchar(nms)),
        msg = "`vars$group_contrasts` must be a non-empty, fully named list"
    )

    records <- Map(
        function(el, label) {
            if (is.character(el)) {
                assert_that(
                    length(el) == 2,
                    msg = paste(
                        "character `vars$group_contrasts` elements must be length-2",
                        "`c(minuend, subtrahend)` vectors"
                    )
                )
                idx <- match(el, orig_levels)
                assert_that(
                    !anyNA(idx),
                    msg = sprintf(
                        "`vars$group_contrasts` references group level(s) not present in the data: %s",
                        paste(el[is.na(idx)], collapse = ", ")
                    )
                )
                assert_that(
                    idx[[1]] != idx[[2]],
                    msg = "`vars$group_contrasts` cannot contrast a group level with itself"
                )
                record(
                    pairwise_weights(idx[[1]], idx[[2]]),
                    label,
                    label,
                    orig_levels[idx[[1]]],
                    orig_levels[idx[[2]]]
                )
            } else if (is.numeric(el)) {
                record(
                    resolve_contrast_weights(el, orig_levels),
                    label,
                    label,
                    NA_character_,
                    NA_character_
                )
            } else {
                stop(paste(
                    "each `vars$group_contrasts` element must be a length-2 character",
                    "vector or a numeric weight vector"
                ))
            }
        },
        group_contrasts,
        nms
    )

    params <- vapply(records, `[[`, character(1), "parameter")
    assert_that(
        !any(grepl("^lsm_", params)),
        msg = "`vars$group_contrasts` names must not start with `lsm_` (reserved for least-squares means)"
    )
    assert_that(
        !any(duplicated(params)),
        msg = "`vars$group_contrasts` contains duplicate contrast names"
    )
    unname(records)
}


#' Resolve a numeric contrast weight vector to full group-level order
#'
#' Expands a (possibly level-named or level-length) numeric weight vector into a full
#' vector over all group levels in factor order, validating that it references known
#' levels, sums to zero and is not trivially zero.
#'
#' @param x Numeric weight vector, either named by group levels (missing levels are
#'   filled with `0`) or of length `length(orig_levels)` in factor order.
#' @param orig_levels Character vector of the group factor levels (in order).
#' @return A numeric vector of length `length(orig_levels)` summing to zero.
#' @keywords internal
resolve_contrast_weights <- function(x, orig_levels) {
    n_lvl <- length(orig_levels)
    w <- numeric(n_lvl)
    if (!is.null(names(x)) && any(nzchar(names(x)))) {
        idx <- match(names(x), orig_levels)
        assert_that(
            !anyNA(idx),
            msg = sprintf(
                "`vars$group_contrasts` weight vector references unknown group level(s): %s",
                paste(names(x)[is.na(idx)], collapse = ", ")
            )
        )
        assert_that(
            !any(duplicated(idx)),
            msg = "`vars$group_contrasts` weight vector names must be unique group levels"
        )
        w[idx] <- as.numeric(x)
    } else {
        assert_that(
            length(x) == n_lvl,
            msg = sprintf(
                "Unnamed `vars$group_contrasts` weight vectors must have one entry per group level (%d)",
                n_lvl
            )
        )
        w <- as.numeric(x)
    }
    assert_that(
        isTRUE(abs(sum(w)) < sqrt(.Machine$double.eps)),
        msg = "`vars$group_contrasts` weight vectors must sum to zero"
    )
    assert_that(
        any(w != 0),
        msg = "`vars$group_contrasts` weight vectors must not be all zero"
    )
    w
}


#' Compute a single ANCOVA linear contrast
#'
#' Evaluates a linear contrast over the group levels as a linear combination of the
#' model coefficients. The group-level weights are mapped onto the model's group
#' coefficients using the factor's own contrast matrix, so the result is independent
#' of the active `contrasts` coding and reduces exactly to the group coefficient for a
#' pairwise contrast versus the reference level (preserving backwards compatibility
#' with the two-group implementation).
#'
#' @param weights Numeric weight vector over the group levels (factor order), summing
#'   to zero.
#' @param beta Numeric vector of model coefficients.
#' @param vcov_mod Variance-covariance matrix of the model coefficients.
#' @param df_res Residual degrees of freedom.
#' @param grp_names Character vector of the coefficient names for the `rbmiGroup` main
#'   effect (columns of `cmat`, in order).
#' @param cmat Contrast matrix of the `rbmiGroup` factor (`n_levels` rows, one column
#'   per group coefficient).
#' @return A list with elements `est`, `se` and `df`.
#'
#' @details
#' The contrast is evaluated at the covariate reference (covariate = 0): covariate
#' main-effect and interaction columns receive zero weight and cancel for a
#' sum-to-zero contrast, so `trt` remains the group main-effect contrast (matching the
#' original two-group behaviour and independent of the `weights` argument). Building
#' the contrast from the factor's contrast matrix rather than by parsing coefficient
#' names keeps it correct under non-default contrast codings (e.g. `contr.sum`). A
#' group coefficient that is missing, aliased (`NA`) or absent from the
#' variance-covariance matrix indicates a rank-deficient design and triggers an error
#' rather than a silently dropped term.
#' @keywords internal
ancova_linear_contrast <- function(
    weights,
    beta,
    vcov_mod,
    df_res,
    grp_names,
    cmat
) {
    assert_that(
        is.numeric(beta),
        !is.null(names(beta)),
        msg = "`beta` must be a named numeric vector"
    )
    assert_that(
        length(weights) == nrow(cmat),
        isTRUE(abs(sum(weights)) < sqrt(.Machine$double.eps)),
        msg = "contrast weights must have one entry per group level and sum to zero"
    )
    assert_that(
        length(grp_names) == ncol(cmat),
        all(grp_names %in% colnames(vcov_mod)),
        !anyNA(beta[grp_names]),
        msg = paste(
            "group coefficients are missing, aliased, or not aligned with the",
            "variance-covariance matrix; the design matrix is rank-deficient"
        )
    )
    # Map the group-level weights onto the model's group coefficients.
    lvec <- as.vector(crossprod(cmat, weights))
    vcov_grp <- vcov_mod[grp_names, grp_names, drop = FALSE]
    list(
        est = sum(lvec * beta[grp_names]),
        se = sqrt(drop(t(lvec) %*% vcov_grp %*% lvec)),
        df = df_res
    )
}
