name: Build latest version Docker images

env:
  REGISTRY: ghcr.io

on:
  schedule:
    - cron: '0 5 1 * *'
  workflow_dispatch:
  push:
    paths:
      - 'misc/docker/**'
      - 'misc/docker/*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Deploy Docker Images

    # Token permissions
    permissions:
      contents: read
      packages: write

    # Build steps
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image tag
        id: vars
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [ "$BRANCH_NAME" = "main" ]; then
            TAG="latest"
          else
            TAG="${BRANCH_NAME}"
          fi
          echo "tag=rbmi:${TAG}" >> $GITHUB_OUTPUT

      - name: debug
        run: |
          echo push = ${{ github.event_name == 'push' }}
          echo tag = ${{ env.REGISTRY }}/${{ github.repository_owner }}:${{ steps.vars.outputs.tag }}


      - name: Build and push image 
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./misc/docker/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}:${{ steps.vars.outputs.tag }}
          build-args: |
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ github.repository_owner }}:latest
          cache-to: type=inline
