

on:
  push:
    paths-ignore:
      - 'misc/**'

name: Check Pushes

jobs:
  testthat:
    runs-on: ubuntu-latest
    container:
      image: gowerc/rbmi:r404
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build src
        uses: ./.github/actions/build-src
      
      - name: testthat
        run: |
          options(crayon.enabled = TRUE, cli.dynamic = FALSE)
          devtools::test(stop_on_failure = TRUE, reporter = testthat::CheckReporter)
        shell: Rscript {0}
