

on: [push]

name: Check Pushes

jobs:
  testthat:
    runs-on: ubuntu-latest
    container:
      image: gowerc/rbmi:r404
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: misc testing
        run: |
          echo ${{ job.container }}
    
      - name: Cache Compiled Stan Code
        id: cache
        uses: actions/cache@v2
        with:
          path: src/*
          key: ${{ job.container }}-${{ hashFiles('inst/stan/MMRM.stan') }}
    
      - name: Compile Stan Code
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          devtools::load_all()
        shell: Rscript {0}
      

      
      - name: Check
        run: |
          options(crayon.enabled = TRUE)
          devtools::test(stop_on_failure=TRUE)
        shell: Rscript {0}
